.catalog:
  name: "Consul"
  version: "0.1.0"
  description: |
    Deploys a HA Consul cluster (1 nodes) with agents and registrator on all nodes
  minimum_rancher_version: "v0.46.0"

consul-server:
  scale: 1
  health_check:
    port: 8500
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    unhealthy_threshold: 1
    strategy: recreateOnQuorum
    request_line: GET /v1/status/leader HTTP/1.0
    healthy_threshold: 1
    response_timeout: 2000

consul-data:
  scale: 1

consul-agent:
  health_check:
    port: 8500
    interval: 10000
    unhealthy_threshold: 1
    strategy: recreate
    request_line: GET /v1/status/leader HTTP/1.0
    healthy_threshold: 1
    response_timeout: 2000
